export const grades = [
  {
    id: 1,
    title: "Toyota Voxy Hybrid V (7 Seaters)",
    price: { value: "127888", unit: "SGD" },
    engineCap: { value: "1797", unit: "cc" },
    power: { value: "98", unit: "bhp" },
    fuelConspt: { value: "23.8", unit: "km/litre" },
    // image: require("../assets/images/toyotaVoxy-1.jpg"),
    // imageHover: require("../assets/images/toyotaVoxy-2.jpg"),
    modelId: "1",
    feat: true
  },
  {
    id: 2,
    title: "Toyota Vellfire 2.5Z Facelift (7 Seater)",
    price: { value: "178888", unit: "SGD" },
    engineCap: { value: "2493", unit: "cc" },
    power: { value: "180", unit: "bhp" },
    fuelConspt: { value: "11.6", unit: "km/litre" },
    // image: require("../assets/images/img1.jpg"),
    // imageHover: require("../assets/images/img1.jpg"),
    modelId: "2",
    feat: false
  },
  {
    id: 3,
    title: "Toyota Vellfire 2.5X Facelift (7 Seater)",
    price: { value: "158888", unit: "SGD" },
    engineCap: { value: "2493", unit: "cc" },
    power: { value: "180", unit: "bhp" },
    fuelConspt: { value: "11.6", unit: "km/litre" },
    // image: require("../assets/images/img1.jpg"),
    // imageHover: require("../assets/images/img1.jpg"),
    modelId: "2",
    feat: false
  },
  ,
  {
    id: 4,
    title: "Toyota Esquire Hybrid GI (7 Seater)",
    price: { value: "132888", unit: "SGD" },
    engineCap: { value: "1797", unit: "cc" },
    power: { value: "98", unit: "bhp" },
    fuelConspt: { value: "23.8", unit: "km/litre" },
    // image: require("../assets/images/img1.jpg"),
    // imageHover: require("../assets/images/img1.jpg"),
    modelId: "3",
    feat: true
  },
  {
    id: 5,
    title: "Toyota C-HR Hybrid S",
    price: { value: "132888", unit: "SGD" },
    engineCap: { value: "1797", unit: "cc" },
    power: { value: "167", unit: "bhp" },
    fuelConspt: { value: "30.2", unit: "km/litre" },
    // image: require("../assets/images/img1.jpg"),
    // imageHover: require("../assets/images/img1.jpg"),
    modelId: "4",
    feat: false
  },
  {
    id: 6,
    title: "Honda Shuffle 1.5G Facelift Sensing",
    price: { value: "77888", unit: "SGD" },
    engineCap: { value: "1496", unit: "cc" },
    power: { value: "130", unit: "bhp" },
    fuelConspt: { value: "17.8", unit: "km/litre" },
    // image: require("..//assets/images/hondaShuttle-1.jpg"),
    // imageHover: require("../assets/images/img1.jpg"),
    modelId: "5",
    feat: true
  },
  {
    id: 7,
    title: "Honda Vezel 1.5X (Facelift)",
    price: { value: "86888", unit: "SGD" },
    engineCap: { value: "1496", unit: "cc" },
    power: { value: "128", unit: "bhp" },
    fuelConspt: { value: "20.0", unit: "km/litre" },
    // image: require("../assets/images/img1.jpg"),
    // imageHover: require("../assets/images/img1.jpg"),
    modelId: "6",
    feat: false
  },
  {
    id: 8,
    title: "Honda Vezel Hybrid X (2019 Facelift)",
    price: { value: "99888", unit: "SGD" },
    engineCap: { value: "1496", unit: "cc" },
    power: { value: "150", unit: "bhp" },
    fuelConspt: { value: "24.2", unit: "km/litre" },
    // image: require("../assets/images/img1.jpg"),
    // imageHover: require("../assets/images/img1.jpg"),
    modelId: "6",
    feat: true
  },
  {
    id: 9,
    title: "Honda Fit 1.3GF",
    price: { value: "65888", unit: "SGD" },
    engineCap: { value: "1339", unit: "cc" },
    power: { value: "97", unit: "bhp" },
    fuelConspt: { value: "24.6", unit: "km/litre" },
    // image: require("../assets/images/img1.jpg"),
    // imageHover: require("../assets/images/img1.jpg"),
    modelId: "7",
    feat: false
  },
  {
    id: 10,
    title: "Suzuki Swift Sport MT",
    price: { value: "88888", unit: "SGD" },
    engineCap: { value: "1371", unit: "cc" },
    power: { value: "138", unit: "bhp" },
    fuelConspt: { value: "16.4", unit: "km/litre" },
    // image: require("../assets/images/suzuki-1.jpg"),
    // imageHover: require("../assets/images/img1.jpg"),
    modelId: "8",
    feat: true
  }
];
