export const models = [ {"id":1, "name": "Toyota Voxy", "image": require("../images/toyotaVoxy-1.jpg"),"imageHover": require("../images/toyotaVoxy-2.jpg"), 
"price": {"value":"127888","unit":"SGD"} , "banner": require("../images/toyota/toyota_voxy.jpg"), "brandId":1},  
{"id":2, "name": "Toyota Vellfire", "image": require("../images/img1.jpg"),"imageHover": require("../images/img1.jpg"),
"price": {"value":"158888","unit":"SGD"}, "brandId":1}, 
{"id":3, "name": "Toyota Esquire", "image": require("../images/img1.jpg"),"imageHover": require("../images/img1.jpg"),
"price": {"value":"132888","unit":"SGD"}, "brandId":1}, 
{"id":4, "name": "Toyota C-HR", "image": require("../images/img1.jpg"),"imageHover": require("../images/img1.jpg"),
"price": {"value":"103888","unit":"SGD"}, "brandId":1}, 
{"id":5, "name": "Honda Shuttle", "image": require("../images/img1.jpg"),"imageHover": require("../images/img1.jpg"),
"price": {"value":"77888","unit":"SGD"}, "brandId":2},
{"id":6, "name": "Honda Vezel", "image": require("../images/img1.jpg"),"imageHover": require("../images/img1.jpg"),
"price": {"value":"86888","unit":"SGD"}, "brandId":2},
{"id":7, "name": "Honda Fit", "image": require("../images/img1.jpg"),"imageHover": require("../images/img1.jpg"),
"price": {"value":"65888","unit":"SGD"}, "brandId":2},
{"id":8, "name": "Suzuki Swift Sport", "image": require("../images/img1.jpg"),"imageHover": require("../images/img1.jpg"),
"price": {"value":"88888","unit":"SGD"}, "brandId":3} ];
