
//PRODUCTS
export const GET_PRODUCT_LIST = "GET_PRODUCT_LIST";
export const GET_PRODUCT_LIST_SUCCESS = "GET_PRODUCT_LIST_SUCCESS";
export const GET_PRODUCT_LIST_FAILURE = "GET_PRODUCT_LIST_FAILURE";

//EXTERIOR
export const GET_EXTERIOR_LIST = "GET_EXTERIOR_LIST";
export const GET_EXTERIOR_LIST_SUCCESS = "GET_EXTERIOR_LIST_SUCCESS";
export const GET_EXTERIOR_LIST_FAILURE = "GET_EXTERIOR_LIST_FAILURE";

//INTERIOR
export const GET_INTERIOR_LIST = "GET_INTERIOR_LIST";
export const GET_INTERIOR_LIST_SUCCESS = "GET_INTERIOR_LIST_SUCCESS";
export const GET_INTERIOR_LIST_FAILURE = "GET_INTERIOR_LIST_FAILURE";