// TEMPORARY: Update selected model
export const SELECTED_PRODUCT_MODEL = "SELECTED_PRODUCT_MODEL"

// Retrieve grades of selected model
export const GET_PRODUCT_GRADES = "GET_PRODUCT_GRADES"
export const GET_PRODUCT_GRADES_SUCCESS = "GET_PRODUCT_GRADES_SUCCESS"
export const GET_PRODUCT_GRADES_FAILURE = "GET_PRODUCT_GRADES_FAILURE"

// Update selected grade
export const SELECTED_PRODUCT_GRADE = "SELECTED_PRODUCT_GRADE"

// Retrieve data of selected grade
export const GET_PRODUCT_GRADE_DATA = "GET_PRODUCT_GRADE_DATA"
export const GET_PRODUCT_GRADE_DATA_SUCCESS = "GET_PRODUCT_GRADE_DATA_SUCCESS"
export const GET_PRODUCT_GRADE_DATA_FAILURE = "GET_PRODUCT_GRADE_DATA_FAILURE"

// Update selected exterior
export const SELECTED_PRODUCT_EXTERIOR = "SELECTED_PRODUCT_EXTERIOR"

// Update selected interior
export const SELECTED_PRODUCT_INTERIOR = "SELECTED_PRODUCT_INTERIOR"

// Update selected rims
export const SELECTED_PRODUCT_RIMS = "SELECTED_PRODUCT_RIMS"

// Update selected rims
export const SELECTED_PRODUCT_ACCESSORIES = "SELECTED_PRODUCT_ACCESSORIES"

