
// Get data of selected model
export const GET_PRODUCT_MODEL_DATA = "GET_PRODUCT_MODEL_DATA";
export const GET_PRODUCT_MODEL_DATA_SUCCESS = "GET_PRODUCT_MODEL_DATA_SUCCESS";
export const GET_PRODUCT_MODEL_DATA_FAILURE = "GET_PRODUCT_MODEL_DATA_FAILURE";

// Retrieve grades of selected model
export const GET_PRODUCT_GRADES = "GET_PRODUCT_GRADES";
export const GET_PRODUCT_GRADES_SUCCESS = "GET_PRODUCT_GRADES_SUCCESS";
export const GET_PRODUCT_GRADES_FAILURE = "GET_PRODUCT_GRADES_FAILURE";

// Update selected grade
export const SELECTED_PRODUCT_GRADE = "SELECTED_PRODUCT_GRADE";

// Get data of selected grade
export const GET_PRODUCT_GRADE_DATA = "GET_PRODUCT_GRADE_DATA";
export const GET_PRODUCT_GRADE_DATA_SUCCESS = "GET_PRODUCT_GRADE_DATA_SUCCESS";
export const GET_PRODUCT_GRADE_DATA_FAILURE = "GET_PRODUCT_GRADE_DATA_FAILURE";

// Update selected exterior
export const SELECTED_PRODUCT_EXTERIOR = "SELECTED_PRODUCT_EXTERIOR";

// Update selected interior
export const SELECTED_PRODUCT_INTERIOR = "SELECTED_PRODUCT_INTERIOR";

// Update selected rims
export const SELECTED_PRODUCT_RIMS = "SELECTED_PRODUCT_RIMS";

// Update selected rims
export const SELECTED_PRODUCT_ACCESSORIES = "SELECTED_PRODUCT_ACCESSORIES";

export const SELECTED_COE_PACKAGE = "SELECTED_COE_PACKAGE";

export const SELECTED_AFTERSALES_PACKAGE = "SELECTED_AFTERSALES_PACKAGE";

// Update total price
export const UPDATE_PRODUCT_TOTAL = "UPDATE_PRODUCT_TOTAL";

// Update loan calculator
export const UPDATE_LOAN_CALCULATOR = "UPDATE_LOAN_CALCULATOR";

// Generate PDF
export const PRINT_CONFIGURATOR = "PRINT_CONFIGURATOR";
export const PRINT_CONFIGURATOR_SUCCESS = "PRINT_CONFIGURATOR_SUCCESS";
export const PRINT_CONFIGURATOR_FAILURE = "PRINT_CONFIGURATOR_FAILURE";

//Get PDF configuration
export const GET_CONFIGURATION = "GET_CONFIGURATION";
export const GET_CONFIGURATION_SUCCESS = "GET_CONFIGURATION_SUCCESS";
export const GET_CONFIGURATION_FAILURE = "GET_CONFIGURATION_FAILURE";


// Featured Cars
export const GET_FEATURED_CARS = "GET_FEATURED_CARS";
export const GET_FEATURED_CARS_SUCCESS = "GET_FEATURED_CARS_SUCCESS";
export const GET_FEATURED_CARS_FAILURE = "GET_FEATURED_CARS_FAILURE";

// Get interest rate
export const GET_INTEREST_RATE = "GET_INTEREST_RATE";
export const GET_INTEREST_RATE_SUCCESS = "GET_INTEREST_RATE_SUCCESS";
export const GET_INTEREST_RATE_FAILURE = "GET_INTEREST_RATE_FAILURE";

export const GET_ALL_MAKE = "GET_ALL_MAKE";
export const GET_ALL_MAKE_SUCCESS = "GET_ALL_MAKE_SUCCESS";
export const GET_ALL_MAKE_FAILURE = "GET_ALL_MAKE_FAILURE";

export const GET_ALL_TAGS = "GET_ALL_TAGS";
export const GET_ALL_TAGS_SUCCESS = "GET_ALL_TAGS_SUCCESS";
export const GET_ALL_TAGS_FAILURE = "GET_ALL_TAGS_FAILURE";

export const GET_ALL_CARS = "GET_ALL_CARS";
export const GET_ALL_CARS_SUCCESS = "GET_ALL_CARS_SUCCESS";
export const GET_ALL_CARS_FAILURE = "GET_ALL_CARS_FAILURE";

export const GET_ALL_PREOWNED_CARS = "GET_ALL_PREOWNED_CARS";
export const GET_ALL_PREOWNED_CARS_SUCCESS = "GET_ALL_PREOWNED_CARS_SUCCESS";
export const GET_ALL_PREOWNED_CARS_FAILURE = "GET_ALL_PREOWNED_CARS_FAILURE";

export const GET_ALL_CONFIG = "GET_ALL_CONFIG";
export const GET_ALL_CONFIG_SUCCESS = "GET_ALL_CONFIG_SUCCESS";
export const GET_ALL_CONFIG_FAILURE = "GET_ALL_CONFIG_FAILURE";