// Retrieve grades of selected model
export const GET_PRODUCT_GRADES = "GET_PRODUCT_GRADES"
export const GET_PRODUCT_GRADES_SUCCESS = "GET_PRODUCT_GRADES_SUCCESS"
export const GET_PRODUCT_GRADES_FAILURE = "GET_PRODUCT_GRADES_FAILURE"

// Update selected grade
export const SELECTED_PRODUCT_GRADE = "SELECTED_PRODUCT_GRADE"

// Retrieve data of selected grade
export const GET_PRODUCT_GRADE_DATA = "GET_PRODUCT_GRADE_DATA"
export const GET_PRODUCT_GRADE_DATA_SUCCESS = "GET_PRODUCT_GRADE_DATA_SUCCESS"
export const GET_PRODUCT_GRADE_DATA_FAILURE = "GET_PRODUCT_GRADE_DATA_FAILURE"

// Retrieve exterior product variants of a selected grade
export const GET_EXTERIOR_LIST = "GET_EXTERIOR_LIST"
export const GET_EXTERIOR_LIST_SUCCESS = "GET_EXTERIOR_LIST_SUCCESS"
export const GET_EXTERIOR_LIST_FAILURE = "GET_EXTERIOR_LIST_FAILURE"

// Update selected exterior
export const SELECTED_PRODUCT_EXTERIOR = "SELECTED_PRODUCT_EXTERIOR"

// Retrieve interior product variants of a selected grade
export const GET_INTERIOR_LIST = "GET_INTERIOR_LIST"
export const GET_INTERIOR_LIST_SUCCESS = "GET_INTERIOR_LIST_SUCCESS"
export const GET_INTERIOR_LIST_FAILURE = "GET_INTERIOR_LIST_FAILURE"

// Retrieve product options of a selected grade
export const GET_PRODUCT_OPTIONS = "GET_PRODUCT_OPTIONS"
export const GET_PRODUCT_OPTIONS_SUCCESS = "GET_PRODUCT_OPTIONS_SUCCESS"
export const GET_PRODUCT_OPTIONS_FAILURE = "GET_PRODUCT_OPTIONS_FAILURE"

