// Retrieve grades of selected model
// export const SAVE_ACCESS_TOKEN = "SAVE_ACCESS_TOKEN"
// export const SAVE_ACCESS_TOKEN_SUCCESS = "SAVE_ACCESS_TOKEN_SUCCESS"
// export const SAVE_ACCESS_TOKEN_FAILURE = "SAVE_ACCESS_TOKEN_FAILURE"

export const LOGOUT_ACCOUNT = "LOGOUT_ACCOUNT";
export const LOGOUT_ACCOUNT_FAILURE = "LOGOUT_ACCOUNT_FAILURE";
export const LOGOUT_ACCOUNT_SUCCESS = "LOGOUT_ACCOUNT_SUCCESS";

export const LOGIN_ACCOUNT = "LOGIN_ACCOUNT";
export const LOGIN_ACCOUNT_SUCCESS = "LOGIN_ACCOUNT_SUCCESS";
export const LOGIN_ACCOUNT_FAILURE = "LOGIN_ACCOUNT_FAILURE";

export const RETRIEVE_USER_PROFILE = "RETRIEVE_USER_PROFILE";
export const RETRIEVE_USER_PROFILE_SUCCESS = "RETRIEVE_USER_PROFILE_SUCCESS";
export const RETRIEVE_USER_PROFILE_FAILURE = "RETRIEVE_USER_PROFILE_FAILURE";

export const UPDATE_USER_PROFILE = "UPDATE_USER_PROFILE";
export const UPDATE_USER_PROFILE_SUCCESS = "UPDATE_USER_PROFILE_SUCCESS";
export const UPDATE_USER_PROFILE_FAILURE = "UPDATE_USER_PROFILE_FAILURE";

export const CHECKOUT_LOGIN = "CHECKOUT_LOGIN";
